Vanilla SVG implementation
teknologi-umum/decimal-clock pull request #58
Opened 2022-02-06 12:24 UTC by krowter

Issue [#22](https://github.com/teknologi-umum/decimal-clock/issues/22)

Note: the .svg file contains JavaScript code, so it needs to be viewed in browser or embedded inside html file with `<object>`

2022-02-06 13:33 UTC, herlangga72 commented
Minta ss dong hehehe

2022-02-06 13:55 UTC, krowter commented
Siap Mas, haha, ini ya 
![Screenshot-220206.gif](https://i.imgur.com/0fYOJxU.gif)

2022-02-06 13:57 UTC, herlangga72 approved these changes
I approve

2022-02-06 14:32 UTC, aldy505 commented
> Minta ss dong hehehe

@herlangga72 m a n j a

2022-02-06 14:35 UTC, ronnygunawan requested changes

2022-02-06 14:35 UTC, ronnygunawan commented on vanilla-svg/dist/clock.svg
> +      animation.beginElement();
Jangan pake animation kaya di README.md. Nanti ketika ada skipped frame jamnya jadi ngga akurat.

2022-02-06 15:02 UTC, herlangga72 commented
> > Minta ss dong hehehe
> 
> @herlangga72 m a n j a

Gw sakit beneran. Seharian diatas kasur.  Sakit panas... Ealah kenapa begini dah

2022-02-06 15:31 UTC, krowter commented on vanilla-svg/dist/clock.svg
> +      animation.beginElement();
Wah baru tahu soal masalah skipped frame ini. 
Sip, sudah saya ganti pakai `requestAnimationFrame`

2022-02-07 04:14 UTC, ronnygunawan approved these changes

2022-02-07 04:31 UTC, merged