Please Review React Redux
teknologi-umum/decimal-clock pull request #64
Opened 2022-03-07 14:54 UTC by afman42

Please Reviewed it @ronnygunawan @rubichandrap @aldy505

2022-03-07 14:55 UTC, aldy505 commented
commit your dist directory. see contributing part on readme: https://github.com/teknologi-umum/decimal-clock#contributing

2022-03-07 14:57 UTC, afman42 commented
oh oke wait

2022-03-07 15:02 UTC, afman42 commented
oke, check it. om @aldy505

2022-03-07 15:21 UTC, afman42 commented
> Beberapa koreksi dan masukan dari saya:
> 
>     1. Yang harusnya dibuatkan reducer adalah `timeOfDay`. Sedangkan `arrOfTen` dan `arrOfHundred` seharusnya constant.
> 
>     2. Selector function jangan dipisah jadi file tersendiri karena itu cuma bakal obscure the code. arrow function untuk `useSelector` itu sudah simple dan straightforward.
> 
>     3. Demonstrasikan kelebihan redux di sini. Logic untuk `requestAnimationFrame` bisa dipindah ke luar component dan di dalamnya kita bisa dispatch langsung ke store instance.
> 
>     4. Sediakan action creator di tiap store agar kita bisa lihat secara visual di intellisense sewaktu import action apa saja yang tersedia.

baik om ronny, saya coba lagi

2022-03-08 05:49 UTC, afman42 commented
cek lagi om @aldy505 @elianiva @ronnygunawan

2022-03-08 05:57 UTC, ronnygunawan requested changes
Request changes:
1. `fractionOfDay` dan `timeString` punya source of truth yang sama yaitu `timeOfDay` jadi jangan dipisah jadi 3 state apalagi 3 redux action. Nanti malah jadi triple the render cost.
2. `requestAnimationFrame` logic bisa dipindah ke `index.js` setelah `store`, sebelum `ReactDOM.render`

2022-03-08 09:11 UTC, afman42 commented
> Request changes:
> 
>     1. `fractionOfDay` dan `timeString` punya source of truth yang sama yaitu `timeOfDay` jadi jangan dipisah jadi 3 state apalagi 3 redux action. Nanti malah jadi triple the render cost.
> 
>     2. `requestAnimationFrame` logic bisa dipindah ke `index.js` setelah `store`, sebelum `ReactDOM.render`

`fractionOfDay` dan `timeString` kembali ke semula ya om @ronnygunawan . dan `requestAnimationFrame` jadikan function ya lalu di export giitu.

2022-03-08 10:32 UTC, ronnygunawan commented
> `fractionOfDay` dan `timeString` kembali ke semula ya om @ronnygunawan

Cukup `timeOfDay` yang disimpan di redux. nanti di function body setelah kita dapatkan nilai dari `timeOfDay` menggunakan `useSelector`, barulah kita calculate `fractionOfDay` dan `timeString`. Jadi kedua value ini adalah computed value.

> dan `requestAnimationFrame` jadikan function ya lalu di export giitu.

```js
const store = ....

function updateTimeOfDay() {
  const timeOfDay = ....
  store.dispatch(setTimeOfDay(timeOfDay));
  requestAnimationFrame(updateTimeOfDay);
}

requestAnimationFrame(updateTimeOfDay);

ReactDOM.render(....
```

2022-03-09 02:52 UTC, afman42 commented
silakan di cek lagi om, @ronnygunawan @aldy505 @elianiva

2022-03-09 07:13 UTC, ronnygunawan requested changes
Koreksi dikit lagi

2022-03-09 07:13 UTC, ronnygunawan commented on react-hooks/cra-redux-implementation/src/DecimalClock.js
> +  const [date, setDate] = useState(new Date());
ngga dipake

2022-03-09 07:13 UTC, ronnygunawan commented on react-hooks/cra-redux-implementation/src/DecimalClock.js
> +  dispatch(setTimeOfDay(date))
ngga dipake

2022-03-09 07:13 UTC, ronnygunawan commented on react-hooks/cra-redux-implementation/src/DecimalClock.js
> +  };
ngga dipake

2022-03-09 07:13 UTC, ronnygunawan commented on react-hooks/cra-redux-implementation/src/DecimalClock.js
> +  }, []);
ngga dipake

2022-03-09 07:31 UTC, afman42 commented
sudah di remove code yang tidak dipakai. tolong di cek lagi @ronnygunawan

2022-03-10 03:39 UTC, ronnygunawan approved these changes
Nice. LGTM

2022-03-10 05:26 UTC, merged