implement qwik
teknologi-umum/decimal-clock pull request #69
Opened 2022-10-12 06:46 UTC by nblfikr

#68

2022-10-14 01:36 UTC, nblfikr commented
hi @aldy505 @elianiva 
i don't know which files are needed, can you review this PR?

2022-10-14 02:43 UTC, elianiva requested changes
sebenernya ngga perlu qwik-city, tapi yoweslah gpp

2022-10-14 02:43 UTC, elianiva commented on qwik/functions/[[path]].ts
> +// @ts-ignore
hapus aja

2022-10-14 02:43 UTC, elianiva commented on qwik/src/components/header/header.css
> +header {
hapus aja filenya

2022-10-14 02:43 UTC, elianiva commented on qwik/src/components/header/header.tsx
> +import { component$, useStylesScoped$ } from '@builder.io/qwik';
ini juga hapus

2022-10-14 02:43 UTC, elianiva commented on qwik/src/components/icons/qwik.tsx
> +export const QwikLogo = () => (
hapus

2022-10-14 02:43 UTC, elianiva commented on qwik/src/routes/index.tsx
> +import { component$ } from '@builder.io/qwik';
hapus aja

2022-10-17 03:49 UTC, nblfikr commented on qwik/src/routes/index.tsx
> +import { component$ } from '@builder.io/qwik';
yg ini gabisa dihapus semua, masih belum tau kenapa, jadi sisa kaya gini
![image](https://user-images.githubusercontent.com/56732307/196085394-134e91b1-74a2-40c2-85c0-e5659877ee5b.png)

2022-10-18 09:42 UTC, elianiva commented on qwik/src/routes/index.tsx
> +import { component$ } from '@builder.io/qwik';
lah kena di file ini ternyata wkwkwk
harusnya biarin aja, component `<Clocktime />` pindahin kesini, jangan di layout

2022-10-19 02:38 UTC, nblfikr commented
kayaknya kaya gini lebih oke ya @elianiva ?

2022-10-19 03:01 UTC, elianiva approved these changes

2022-10-19 03:01 UTC, merged